import { Component, OnInit, ViewEncapsulation, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-editor-insert-code',
  templateUrl: './insert-code.component.html',
  styleUrls: ['./insert-code.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class InsertCodeComponent implements OnInit {

  // properties
  @Input() data: { code: string, lang: string };
  @Output('onSubmit') onSubmit = new EventEmitter<string>();

  constructor() { }

  ngOnInit() {
    if (!this.data) {
      this.data = { code: '', lang: '' };
    }

  }

  /** Emit code to parent component */
  private submit() {
    this.onSubmit.emit(this.getData());
  }

  /** Get code generated by user
   * @returns formatted code tag html
   */
  public getData(): string {
    let code = '';
    if (this.data.lang) {
      code = '<pre class="language-' + this.data.lang + '">' + (this.data.code || '') + '</pre>';
    } else {
      code = '<pre>' + (this.data.code || '') + '</pre>';
    }
    return code;
  }
}
